name: Run Daily Notebook

on:
  schedule:
    - cron: '30 6 * * *'  # 11:30 AM IST = 6:00 AM UTC
  workflow_dispatch:      # Allows manual run

jobs:
  execute-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install papermill

      - name: Run notebook
        run: |
          papermill NegativeNewsScraper.ipynb output.ipynb
